name: Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        arch: [arm64, x64]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - name: Sync app version from tag
        run: node ./.erb/scripts/sync-app-version.js
        env:
          VERSION: ${{ github.ref_name }}
      - run: npm run build
      - run: npm run rebuild
        env:
          npm_config_target_arch: ${{ matrix.arch }}
      - run: npx electron-builder --publish always --${{ matrix.arch }} -c.mac.identity=null -c.mac.type=development -c.mac.target=zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false
